#!/usr/bin/env python3

import argparse
import sqlite3
import re


def print_coins(db, format):
    con = sqlite3.connect(db)
    con.row_factory = sqlite3.Row
    cur = con.cursor()
    fields = list(set(re.findall('{([^}]*)}', format)))
    cur.execute(
        f'SELECT * FROM coins ORDER BY title ASC').fetchone()
    for coin in cur.fetchall():
        out = format
        for field in fields:
            out = out.replace(f'{{{field}}}', str(coin[field]))
        print(out.replace('\\n', '\n'))
    con.close()


def main():
    parser = argparse.ArgumentParser(description='OpenNusmismat Print')
    parser.add_argument('--db',
                        type=str,
                        required=True,
                        help='Path to OpenNumismat database')
    parser.add_argument('--format',
                        type=str,
                        default='{title} ({diameter}mm, {weight}g). {mint} mint. {obversedesign} / {reversedesign}.',
                        help='Print format')
    args = parser.parse_args()
    print_coins(args.db, args.format)


if __name__ == '__main__':
    main()
